- op: add
  path: /spec/params/-
  value:
    name: GDRIVE_FOLDER_ID
    type: string
    description: "Google Drive folder ID for uploading SAST results (optional)"
    default: ""
- op: add
  path: /spec/params/-
  value:
    name: GDRIVE_SA_FILE_NAME
    type: string
    description: "Optional GDrive SA file name"
    default: "service_account.json"
- op: add
  path: /spec/tasks/0/params/-
  value:
    name: GDRIVE_FOLDER_ID
    value: "$(params.GDRIVE_FOLDER_ID)"
- op: add
  path: /spec/tasks/0/params/-
  value:
    name: GDRIVE_SA_FILE_NAME
    value: "$(params.GDRIVE_SA_FILE_NAME)"
