apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: sast-ai-workflow-pipelinerun
spec:
  params:
    - name: STORAGE_TYPE
      value: "s3"
    - name: S3_BUCKET_NAME
      value: "S3_BUCKET_NAME_PLACEHOLDER"
