apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pipeline.yaml
  - tasks/execute_sast_ai_workflow.yaml
  # Upload scripts ConfigMaps
  - ../scripts/upload_to_drive_cm.yaml
  - ../scripts/upload_to_gcs_cm.yaml
  - ../scripts/upload_to_s3_output_cm.yaml

